# Generated by Django 5.1.5 on 2025-01-19 12:19

import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус ДДС',
                'verbose_name_plural': 'Статусы ДДС',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкатегории')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('subcategories', models.ManyToManyField(related_name='categories', to='app_cash_flow.subcategory', verbose_name='Подкатегории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название типа')),
                ('categories', models.ManyToManyField(related_name='types', to='app_cash_flow.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Тип ДДС',
                'verbose_name_plural': 'Типы ДДС',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата и время создания записи')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ДДС (в рублях)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('category', smart_selects.db_fields.ChainedForeignKey(chained_field='transaction_type', chained_model_field='types', on_delete=django.db.models.deletion.CASCADE, to='app_cash_flow.category', verbose_name='Категория')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cash_flow.status', verbose_name='Статус ДДС')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='categories', on_delete=django.db.models.deletion.CASCADE, to='app_cash_flow.subcategory', verbose_name='Подкатегория')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cash_flow.transactiontype', verbose_name='Тип ДДС')),
            ],
            options={
                'verbose_name': 'ДДС',
                'verbose_name_plural': 'ДДС',
            },
        ),
    ]
